import React, {useEffect, useLayoutEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import projects from './projects.json';
import './style.css';

const Arrow=()=> <span aria-hidden="true">↗</span>;
const heroProjects=['baochao','wangshan','shengboke','yosemite','lighting'].map(id=>projects.find(p=>p.id===id));
function App(){
 const [route,setRoute]=useState(location.hash),[copied,setCopied]=useState(false),[paused,setPaused]=useState(()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches),[slide,setSlide]=useState(0);
 useEffect(()=>{const update=()=>{setRoute(location.hash);if(location.hash.startsWith('#project/'))window.scrollTo(0,0)};window.addEventListener('hashchange',update);return()=>window.removeEventListener('hashchange',update)},[]);
 const project=projects.find(p=>route===`#project/${p.id}`);
 useLayoutEffect(()=>{const root=document.documentElement;const theme=project?.theme||'dark';root.dataset.projectTheme=project?theme:'home';root.style.setProperty('--project-background',project?.background||(theme==='light'?'#f5f5f3':'#101111'));const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=project?.background||(theme==='light'?'#f5f5f3':'#101111');return()=>{delete root.dataset.projectTheme;root.style.removeProperty('--project-background')}},[project]);

 useEffect(()=>{document.title=project?`${project.name} — 张宏志 HZ`:'张宏志 HZ — 室内设计师';if(!project&&route){requestAnimationFrame(()=>document.getElementById(route.slice(1))?.scrollIntoView())}},[route,project]);
 useEffect(()=>{if(paused||project)return;let alive=true;const timer=setInterval(()=>{const next=(slide+1)%heroProjects.length;const image=new Image();image.onload=()=>{if(alive)setSlide(next)};image.src=heroProjects[next].images[0]},5500);return()=>{alive=false;clearInterval(timer)}},[paused,project,slide]);
 async function copy(){try{await navigator.clipboard.writeText('z595654303');setCopied(true);setTimeout(()=>setCopied(false),2500)}catch{setCopied(false)}}
 const toggle=()=>setPaused(value=>!value);
 return <><header className={project?'solid':''}><a className="logo" href="#home" aria-label="张宏志 首页"><img className="brand-mark" src="/assets/hz-logo.png" alt=""/><span>张宏志<br/>INTERIOR DESIGNER</span></a><nav aria-label="主导航"><a href="#about">关于我 <small>01</small></a><a href="#work">精选作品 <small>02</small></a><a href="#contact">联系 <small>03</small></a></nav><a className="contact-button" href="#contact">聊聊你的项目 <Arrow/></a></header>
 {project?<main className="detail wrap"><a className="back" href="#work">← 返回精选作品</a><div className="project-heading"><div><p className="kicker">PROJECT / {project.city.toUpperCase()}</p><h1>{project.name}</h1></div><p>{project.kind} / {project.area} m² / {project.year}</p></div>{project.note&&<p className="project-note">{project.note}</p>}<div className="detail-images">{project.images.map((image,i)=><figure key={image}><img src={image} alt={`${project.name} · 项目图 ${i+1}`} loading={i?'lazy':'eager'}/><figcaption>{String(i+1).padStart(2,'0')} / {String(project.images.length).padStart(2,'0')}<span>{project.name}</span></figcaption></figure>)}</div><a className="text-link" href="#work">返回作品列表 <Arrow/></a></main>:<main>
 <section className="hero" id="home"><div className="hero-slideshow" aria-hidden="true">{heroProjects.map((p,i)=><img key={p.id} className={i===slide?'hero-slide active':'hero-slide'} src={p.images[0]} alt="" fetchPriority={i===0?'high':'low'} decoding="async"/>)}</div><div className="hero-shade"/><div className="hero-body wrap"><div className="hero-topline"><span>ZHANG HONGZHI / PORTFOLIO</span><span>2022 — 2026</span></div><p className="hero-role">室内设计师 · 空间 / 光影 / 材质</p><h1 className="hero-quote">细节不仅是细节，<br/><span>它们构成了设计本身。</span></h1><p className="quote-author">— 查尔斯·伊姆斯</p><div className="hero-bottom"><a className="hero-link" href="#work">探索我的作品 <Arrow/></a><p>从概念到落地，<br/>寻找空间与人的恰当关系。</p></div></div><div className="hero-foot wrap"><span>FEATURED / {heroProjects[slide].city} · {heroProjects[slide].name} / {String(slide+1).padStart(2,'0')}</span><button onClick={toggle} aria-label={paused?'播放作品轮播':'暂停作品轮播'}>{paused?'播放轮播 ▷':'暂停轮播 Ⅱ'}</button><a href="#about">SCROLL TO EXPLORE ↓</a></div></section>
 <section className="about wrap section resume-page" id="about" aria-labelledby="resume-title">
 <div className="resume-contact-line"><a href="tel:18366752050">183 6675 2050</a><a href="mailto:zhanghz0523@gmail.com">zhanghz0523@gmail.com</a><span>微信：z595654303</span></div>
 <h2 className="resume-title" id="resume-title">ABOUT ME<span>关于我</span></h2>
 <div className="resume-layout"><div className="resume-main"><img className="brand-mark resume-brand" src="/assets/hz-logo.png" alt="HZ"/>
 <section className="resume-block"><h3>经历 <span>/ EXPERIENCE</span></h3><article className="resume-job"><h4>东易日盛｜设计师助理 · 效果图表现师</h4><p className="resume-date">2021.09 — 2022.05 / 青岛</p><p>协助主创完成家装全案方案。<br/>负责平面优化、SU 建模、效果图渲染、方案 PPT 排版，对接客户调整空间落地细节。</p></article><article className="resume-job"><h4>北京营造清美建筑设计有限公司｜空间设计师 · 效果图表现师</h4><p className="resume-date">2022.07 — 至今 / 北京</p><p>独立负责私宅、商业展厅、办公会所类项目。<br/>统筹前期概念推演、平面方案、效果图输出，配合施工团队完成落地跟进，兼顾手绘概念表达与写实渲染。</p></article></section>
 <section className="resume-block"><h3>技能 <span>/ SKILLS</span></h3><ul className="resume-tool-list"><li>SketchUp <span>（Enscape）</span></li><li>SketchBook</li><li>AutoCAD</li><li>3ds Max <span>（Corona）</span></li><li>Photoshop</li><li>AI <span>（前期概念、分析、渲染）</span></li></ul></section>
 <section className="resume-block"><h3>优势 <span>/ ADVANTAGES</span></h3><p>擅长全流程室内空间设计与方案创意思维。<br/>涵盖前期场地分析、平面方案规划、概念 PPT 方案输出；<br/>SU 三维建模推敲、3ds Max / Corona 写实渲染与手绘表达。<br/>参与并独立推进私宅、商业、展厅、办公、会所等多类型项目设计。</p></section></div>
 <aside className="resume-person"><div><img className="resume-portrait" src="/assets/portrait-clear.png" alt="室内设计师张宏志"/><div className="resume-identity"><p>ZHANG HONGZHI</p><h3>张宏志</h3><time className="resume-birthday" dateTime="1997-05-23">1997.05.23</time><span>室内设计师 / 北京</span></div><div className="resume-education"><p>青岛农业大学（环艺 · 本科）</p><span>QINGDAO AGRICULTURAL UNIVERSITY</span></div><div className="resume-practice"><p>空间设计 / 视觉设计 / 绘画 / 摄影</p><span>SPACE DESIGN / VISUAL DESIGN<br/>PAINTING / PHOTOGRAPHY</span></div></div><blockquote className="resume-quote"><p>细节不仅是细节，<br/>它们构成了设计本身。</p><cite>— 查尔斯·伊姆斯</cite></blockquote></aside></div>
 </section>
 <section className="work wrap section" id="work"><div className="section-label"><span>02 / PROJECT ARCHIVE</span><span>2022 — 2026</span></div><div className="archive-heading"><h2>作品档案</h2><p>从居住的日常，到公共空间的体验。</p></div>{[{id:'residential',name:'私宅项目',en:'PRIVATE RESIDENCE',items:projects.filter(p=>p.kind==='私宅空间')},{id:'commercial',name:'工装项目',en:'COMMERCIAL & PUBLIC',items:projects.filter(p=>p.kind!=='私宅空间')}].map(group=><section className="project-group" key={group.id} aria-labelledby={group.id}><div className="group-heading"><h3 id={group.id}>{group.name}<span>{group.en}</span></h3><span>{String(group.items.length).padStart(2,'0')} PROJECTS</span></div><div className="projects archive-grid">{group.items.map((p,i)=><a className="project-card" href={`#project/${p.id}`} key={p.id}><div className="project-image"><img src={p.images[0]} alt={`${p.city} · ${p.name}项目封面`} loading="lazy"/></div><div className="project-caption"><span className="index">{String(i+1).padStart(2,'0')}</span><div><h3>{p.name}</h3><p>{p.city} / {p.kind} · {p.area} m²</p><span className="archive-year">{p.year}{p.note==='毕业设计'?' / 毕业设计':''}</span></div></div></a>)}</div></section>)}</section>
 <section className="contact section contact-minimal" id="contact"><div className="wrap"><div className="section-label"><span>03 / CONTACT</span></div><div className="contact-center"><p className="contact-overline">张宏志 / 室内设计师</p><h2>保持联系。</h2><a className="contact-email" href="mailto:zhanghz0523@gmail.com">zhanghz0523@gmail.com <Arrow/></a></div><div className="contact-baseline"><a href="tel:18366752050"><span>电话</span>183 6675 2050</a><button onClick={copy}><span>微信 / 点击复制</span>{copied?'已复制微信号':'z595654303'}</button></div><span className="sr-only" role="status">{copied?'微信号已复制':''}</span></div></section>
 </main>}<footer className="wrap"><a className="footer-logo" href="#home"><img className="brand-mark" src="/assets/hz-logo.png" alt="HZ"/></a><span>© 2026 · 室内设计 / 视觉表达</span><a href={project?'#work':'#home'}>{project?'全部作品':'返回顶部'} ↑</a></footer></>
}
createRoot(document.getElementById('root')).render(<App/>);
